IA_Config {
 m_sDesiredEnemyFactionKeys {
  "RHS_AFRF"
 }
 m_sDesiredEnemyVehicleFactionKeys {
  "RHS_AFRF"
 }
 m_aGenericHeliOverridePrefabs {
  "{70BAEEFC2D3FEE64}Prefabs/Vehicles/Helicopters/UH1H/UH1H.et"
  "{AF950919C81D91B4}Prefabs/Vehicles/Helicopters/AH6M/MH6M.et"
 }
 m_aAttackHeliOverridePrefabs {
  "{CB4D4CF7E887B2D0}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HEDP.et"
  "{823CA4130CE90077}Prefabs/Vehicles/Helicopters/AH6M/AH6M_RKT.et"
  "{A317D959A4248173}Prefabs/Vehicles/Helicopters/AH6M/AH6M_GAU19.et"
  "{F38B0D1637736312}Prefabs/Vehicles/Helicopters/AH64D/AH64D_AGM65_X2.et"
  "{397971C2026D588F}Prefabs/Vehicles/Helicopters/AH64D/AH64D_AGM114L_X2.et"
 }
 m_aTransportHeliOverridePrefabs {
  "{DDDD9B51F1234DF3}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed.et"
  "{00BC1E407D536A34}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_sharkNose.et"
  "{AF950919C81D91B4}Prefabs/Vehicles/Helicopters/AH6M/MH6M.et"
 }
 m_aVehicleCarOverridePrefabs {
  "{23FB589C8BF6EC6E}Prefabs/Vehicles/Wheeled/M998/M998_covered_long_USAF.et"
  "{CC55611936C21F25}Prefabs/Vehicles/Wheeled/M998/M1025_USAF.et"
  "{3277F8B1FA06A2BC}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_USAF.et"
  "{FA6820A9A52CD05B}Prefabs/Vehicles/Wheeled/M998/M1025_armed_M2HB_MDO_USAF.et"
  "{D951BEDA2CBC56BC}Prefabs/Vehicles/Wheeled/JLTV/CROWS_1/M134/JLTV_CROWS_M134_Olive.et"
  "{423EA86BC26F5128}Prefabs/Vehicles/Wheeled/JLTV/CROWS_1/M2HB/JLTV_CROWS_Olive.et"
  "{225A9305129485F1}Prefabs/Vehicles/Wheeled/JLTV/CROWS_2/JLTV_CROWSII_Olive.et"
  "{65FE6DD2E27E366E}Prefabs/Vehicles/Wheeled/JLTV/CROWS_2/Javelin/JLTV_CROWSII_Javelin_Olive.et"
  "{38BB7CA1E7013D8D}Prefabs/Vehicles/Wheeled/JLTV/OGPK/M134/JLTV_OGPK_M134_Olive.et"
  "{36EA87CEC1BE77E0}Prefabs/Vehicles/Wheeled/JLTV/OGPK/M2HB/JLTV_OGPK_Olive.et"
 }
 m_aVehicleArmorOverridePrefabs {
  "{3312ADBF53A16DD8}Prefabs/Vehicles/Wheeled/LAV25/LAV25_RHS.et"
  "{A6783FAA5D516D68}Prefabs/Vehicles/Wheeled/Stryker/M1128/Stryker_MGS.et"
  "{8C56ABBA9DFE03D8}Prefabs/Vehicles/Tracked/M1A1/M1A1_TUSK.et"
  "{56DB823510AFCD8D}Prefabs/Vehicles/Tracked/M1A1/M1A1_Net.et"
  "{F9FF4BDD5F962A2D}Prefabs/Vehicles/Tracked/M1A2/M1A2_TUSK.et"
  "{DF904EC4C4A8CB7D}Prefabs/Vehicles/Tracked/M1A2/M1A2_TUSKII.et"
 }
 m_aAPC_OverridePrefabs {
  "{3312ADBF53A16DD8}Prefabs/Vehicles/Wheeled/LAV25/LAV25_RHS.et"
  "{E3DD72FD06BA2320}Prefabs/Vehicles/Wheeled/Stryker/M1126/CROWS/Stryker_CROWS.et"
  "{91325B8E3EE8E4DD}Prefabs/Vehicles/Wheeled/Stryker/M1126/CROWS/Javelin/Stryker_CROWS_Javelin.et"
  "{45DDFA40E1CB6B82}Prefabs/Vehicles/Wheeled/Stryker/M1296/Stryker_Dragoon.et"
 }
 m_aTruckOverridePrefabs {
  "{F1FBD0972FA5FE09}Prefabs/Vehicles/Wheeled/M923A1/M923A1_transport.et"
  "{81FDAD5EB644CC3D}Prefabs/Vehicles/Wheeled/M923A1/M923A1_transport_covered.et"
 }
 m_aMedicalVehicleOverridePrefabs {
  "{00C9BBE426F7D459}Prefabs/Vehicles/Wheeled/M998/M997_maxi_ambulance.et"
 }
 m_aMedicalCarOverridePrefabs {
  "{00C9BBE426F7D459}Prefabs/Vehicles/Wheeled/M998/M997_maxi_ambulance.et"
 }
 m_fCivilianCountMultiplier 0.6
 m_fCivilianVehicleCountMultiplier 0.5
}