SCR_MissionHeader : "{2D98D7D02FFABBA9}Missions/EveronInvadeandAnnex.conf" {
 World "{AAB9BEE25D61DB91}Worlds/IA_Everon_TFD.ent"
 m_sName "Mike's Invade And Annex (TFD Edition)"
 m_sAuthor "TheTimidShade"
 m_sIcon "{C404DA6B9845E4B9}Images/thumb.edds"
 m_sLoadingScreen "{C404DA6B9845E4B9}Images/thumb.edds"
 m_sPreviewImage "{C404DA6B9845E4B9}Images/thumb.edds"
}