SCR_MissionHeader : "{2D98D7D02FFABBA9}Missions/EveronInvadeandAnnex.conf" {
 World "{AAB9BEE25D61DB91}Worlds/IA_Everon_TFD.ent"
 m_sName "Mike's Invade And Annex (TFD Edition)"
 m_sAuthor "TheTimidShade"
}